[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "psycopg-binary>=3.2.10",
    "pydantic>=2.11.9",
    "sqlalchemy>=2.0.43",
    "uvicorn[standard]>=0.35.0",
]
