dependencies = [
    # DB & ORM
    "asyncpg>=0.30.0",
    "tortoise-orm>=0.25.1",
    "aerich>=0.9.1",

    # 보안 & 인증
    "bcrypt<4.0.0",
    "passlib[bcrypt]<4.0.0",
    "pyjwt>=2.10.1",

    # 웹 프레임워크
    "fastapi>=0.116.1",
    "uvicorn[standard]>=0.35.0",

    # 메일 발송
    "fastapi-mail>=1.5.0",

    # 환경 변수 & 설정
    "python-dotenv>=1.0.1",
    "tomlkit>=0.13.3",

    # 캐시/세션
    "redis>=6.4.0",

    # 데이터 검증
    "pydantic[email]>=2.11.9",

    # 외부 API
    "httpx>=0.27.0",
    "feedparser>=6.0.11",

    # 엑셀 & 데이터 처리
    "pandas>=2.2.3",
    "openpyxl>=3.1.5",
]
