name: 🐛 Bug Report
description: 간단한 버그 리포트
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    id: situation
    attributes:
      label: 상황
      description: 버그가 발생한 상황을 적어주세요
      placeholder: 예) 로그인 버튼 클릭 시 500 오류
    validations:
      required: true

  - type: textarea
    id: resolution
    attributes:
      label: 해결 상황
      description: 시도한 해결 방법/로그 등
      placeholder: 예) 캐시 삭제, 재시도, 에러 로그 첨부

  - type: dropdown
    id: solved
    attributes:
      label: 해결 완료
      options:
        - 미해결
        - 해결 완료
    validations:
      required: true